apiVersion: apps/v1
kind: Deployment
metadata:
  name: outing-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outing-profile-service
  template:
    metadata:
      labels:
        app: outing-profile-service
    spec:
      containers:
        - name: outing-profile-service
          image: nikaklimenchuk/outing-profile-service:v1.2
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/outing_profiles
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: outing-profile-service
spec:
  selector:
    app: outing-profile-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
